version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:300

    backend:
      build: ./backend
      ports:
        - "3000:3000"
      environment:
        - DATABASE_URL=postgresql://oekaki:password@db:5432/oekaki_db
      depengs_on:
        -db

    db:
      image: postgres:16-alpine
      envrionment:
        - POSTGRES_USER=oekaki
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=oekaki_db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

volumes:
  postgre_data:
